name: python-app-3-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master

# allow pushing from the self-hosted runner
permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: obilotiti/python-app-3:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          # use your org PAT so the working copy is writable
          token: ${{ secrets.AUTH_GITHUB_TOKEN }}

      - name: Install kubectl
        shell: bash
        run: |
          # Install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Modify values file
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.commit_id }}
          # Use Mike Farah yq (supports -i). Avoid the Python yq wrapper.
          if ! command -v yq >/dev/null 2>&1; then
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi
          TAG=${{ needs.ci.outputs.commit_id }}
          yq -i ".image.tag = \"${TAG}\"" charts/python-app-3/values-dev.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: charts/python-app-3/values-dev.yaml
          message: "Updates values.yaml with commit ${{ needs.ci.outputs.commit_id }}"
          default_author: github_actions
          pull: "--rebase --autostash"
          push: true
          branch: master

      - name: Install argocd
        shell: bash
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Configure kubectl access
        shell: bash
        run: |
          # Verify kubectl can access the cluster
          kubectl cluster-info
          kubectl get pods -n argocd

      - name: argocd login
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}

      - name: Ensure argocd repo and app
        shell: bash
        run: |

          # Connects the argocd repo
          repo="https://github.com/obilotiti-com/python-app-3.git"
          argocd repo list | grep -q $repo || argocd repo add $repo

          # Creates the argocd app
          argocd app get python-app-3 || argocd app create python-app-3 \
            --repo $repo \
            --path charts/python-app-3 \
            --dest-namespace dev \
            --dest-server https://kubernetes.default.svc \
            --values values-dev.yaml \
            --revision master \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      - name: Argocd app sync
        shell: bash
        run: |
          argocd app sync python-app-3
          argocd app wait python-app-3 --timeout 180